const types = {
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',

  SAVE_ALBUM: 'SAVE_ALBUM',
  REMOVE_ALBUM: 'REMOVE_ALBUM',

  GET_SAVED_ALBUMS: 'GET_SAVED_ALBUMS',
};

export default types;
